# Generated by Django 6.1.1 on 2026-09-15 00:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("empresas", "0002_empresa_uuid"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StatusAnalise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="criado em")),
                ("atualizado_em", models.DateTimeField(auto_now=True, verbose_name="atualizado em")),
                ("nome", models.CharField(max_length=50, verbose_name="nome")),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("em_analise", "Em análise"),
                            ("pendente", "Pendente"),
                            ("aprovado", "Aprovado"),
                            ("reprovado", "Reprovado"),
                            ("cancelado", "Cancelado"),
                        ],
                        max_length=20,
                        verbose_name="categoria",
                    ),
                ),
                ("ordem", models.PositiveSmallIntegerField(default=0, verbose_name="ordem")),
                ("ativo", models.BooleanField(default=True, verbose_name="ativo")),
            ],
            options={
                "verbose_name": "status de análise",
                "verbose_name_plural": "status de análise",
                "ordering": ["ordem", "nome"],
            },
        ),
        migrations.CreateModel(
            name="Analise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, unique=True, verbose_name="identificador público"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="criado em")),
                ("atualizado_em", models.DateTimeField(auto_now=True, verbose_name="atualizado em")),
                (
                    "valor_solicitado",
                    models.DecimalField(decimal_places=2, max_digits=12, verbose_name="valor solicitado"),
                ),
                ("observacoes", models.TextField(blank=True, verbose_name="observações")),
                ("versao", models.PositiveIntegerField(default=0, verbose_name="versão")),
                (
                    "analista",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="analises_realizadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "consorciorista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="analises_encaminhadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="analises",
                        to="empresas.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "análise",
                "verbose_name_plural": "análises",
                "ordering": ["-criado_em"],
            },
        ),
    ]
