# Generated by Django 6.1.1 on 2026-09-15 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("analises", "0001_initial"),
        ("empresas", "0002_empresa_uuid"),
        ("pessoas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="analise",
            name="pessoa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="analises", to="pessoas.pessoa"
            ),
        ),
        migrations.AddField(
            model_name="statusanalise",
            name="empresa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="status_analise",
                to="empresas.empresa",
            ),
        ),
        migrations.AddField(
            model_name="analise",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="analises",
                to="analises.statusanalise",
            ),
        ),
        migrations.AddIndex(
            model_name="statusanalise",
            index=models.Index(fields=["empresa", "categoria"], name="idx_status_empresa_categoria"),
        ),
        migrations.AddConstraint(
            model_name="statusanalise",
            constraint=models.UniqueConstraint(fields=("empresa", "nome"), name="uniq_status_empresa_nome"),
        ),
        migrations.AddIndex(
            model_name="analise",
            index=models.Index(fields=["empresa", "-criado_em"], name="idx_analise_empresa_criado"),
        ),
        migrations.AddIndex(
            model_name="analise",
            index=models.Index(fields=["empresa", "status"], name="idx_analise_empresa_status"),
        ),
        migrations.AddIndex(
            model_name="analise",
            index=models.Index(fields=["empresa", "consorciorista"], name="idx_analise_empresa_consorc"),
        ),
        migrations.AddConstraint(
            model_name="analise",
            constraint=models.CheckConstraint(
                condition=models.Q(("valor_solicitado__gt", 0)), name="ck_analise_valor_positivo"
            ),
        ),
    ]
