# Generated by Django 6.1.1 on 2026-09-15 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analises", "0002_initial"),
        ("empresas", "0002_empresa_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analise",
            name="empresa",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="analises",
                to="empresas.empresa",
            ),
        ),
        migrations.AlterField(
            model_name="statusanalise",
            name="empresa",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="status_analise",
                to="empresas.empresa",
            ),
        ),
    ]
