# Generated by Django 6.1.1 on 2026-09-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("cnpj", models.CharField(max_length=14, unique=True)),
                ("ativa", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "empresa",
                "verbose_name_plural": "empresas",
                "ordering": ["nome"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("cnpj__regex", "^\\d{14}$")), name="ck_empresa_cnpj_digitos"
                    )
                ],
            },
        ),
    ]
