# Generated by Django 6.1.1 on 2026-09-15 00:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("empresas", "0002_empresa_uuid"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pessoa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, unique=True, verbose_name="identificador público"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="criado em")),
                ("atualizado_em", models.DateTimeField(auto_now=True, verbose_name="atualizado em")),
                ("nome_completo", models.CharField(max_length=150, verbose_name="nome completo")),
                ("cpf", models.CharField(max_length=11, verbose_name="CPF")),
                ("data_nascimento", models.DateField(verbose_name="data de nascimento")),
                (
                    "renda_mensal",
                    models.DecimalField(decimal_places=2, max_digits=12, verbose_name="renda mensal"),
                ),
                ("telefone", models.CharField(blank=True, max_length=11, verbose_name="telefone")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="e-mail")),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pessoas",
                        to="empresas.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "pessoa",
                "verbose_name_plural": "pessoas",
                "ordering": ["nome_completo"],
                "indexes": [
                    models.Index(fields=["empresa", "nome_completo"], name="idx_pessoa_empresa_nome")
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("empresa", "cpf"), name="uniq_pessoa_empresa_cpf"),
                    models.CheckConstraint(
                        condition=models.Q(("cpf__regex", "^\\d{11}$")), name="ck_pessoa_cpf_digitos"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("renda_mensal__gte", 0)), name="ck_pessoa_renda_nao_negativa"
                    ),
                ],
            },
        ),
    ]
