# Generated by Django 6.1.1 on 2026-09-15 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("empresas", "0002_empresa_uuid"),
        ("pessoas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pessoa",
            name="empresa",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pessoas",
                to="empresas.empresa",
            ),
        ),
    ]
